;this file for FamiTone2 library generated by FamiStudio

untitled_music_data:
	.db 1
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,307,256

.instruments:
	.db $f0 ;instrument 00 (Bass)
	.dw .env1, .env0, .env0
	.db $00

.samples:
.env0:
	.db $c0,$7f,$00,$00
.env1:
	.db $cf,$7f,$00,$00

.song0ch0:
	.db $fb, $01
.song0ch0loop:
.ref0:
	.db $80,$4e,$4e,$4e,$bb,$00,$4e,$83,$4e,$93,$00,$4e,$9b,$00,$54,$9d,$00,$83,$52,$93,$01,$4e,$91,$01,$4a,$a3
.ref1:
	.db $83,$00,$83,$52,$9b,$01,$4e,$95,$00,$4a,$93,$00,$48,$bd,$01,$4e,$8b,$54,$8d,$54,$8d,$58,$01,$4a,$87,$52,$9b,$00
.ref2:
	.db $81,$48,$a3,$01,$46,$95,$44,$f9,$bf
.ref3:
	.db $f9,$f9,$8b
.ref4:
	.db $f9,$f9,$8b
.ref5:
	.db $f9,$f9,$8b
.ref6:
	.db $f9,$f9,$8b
.ref7:
	.db $a7,$00,$f9,$db
.ref8:
	.db $f9,$f9,$8b
.ref9:
	.db $f9,$f9,$8b
.ref10:
	.db $f9,$f9,$8b
.ref11:
	.db $f9,$f9,$8b
.ref12:
	.db $f9,$f9,$8b
.ref13:
	.db $f9,$f9,$8b
.ref14:
	.db $f9,$f9,$8b
.ref15:
	.db $f9,$f9,$8b
	.db $fd
	.dw .song0ch0loop

.song0ch1:
.song0ch1loop:
.ref16:
	.db $f9,$f9,$8b
.ref17:
	.db $f9,$f9,$8b
.ref18:
	.db $f9,$f9,$8b
.ref19:
	.db $f9,$f9,$8b
.ref20:
	.db $f9,$f9,$8b
.ref21:
	.db $f9,$f9,$8b
.ref22:
	.db $f9,$f9,$8b
.ref23:
	.db $f9,$f9,$8b
.ref24:
	.db $f9,$f9,$8b
.ref25:
	.db $f9,$f9,$8b
.ref26:
	.db $f9,$f9,$8b
.ref27:
	.db $f9,$f9,$8b
.ref28:
	.db $f9,$f9,$8b
.ref29:
	.db $f9,$f9,$8b
.ref30:
	.db $f9,$f9,$8b
.ref31:
	.db $f9,$f9,$8b
	.db $fd
	.dw .song0ch1loop

.song0ch2:
.song0ch2loop:
.ref32:
	.db $f9,$f9,$8b
.ref33:
	.db $f9,$f9,$8b
.ref34:
	.db $f9,$f9,$8b
.ref35:
	.db $f9,$f9,$8b
.ref36:
	.db $f9,$f9,$8b
.ref37:
	.db $f9,$f9,$8b
.ref38:
	.db $f9,$f9,$8b
.ref39:
	.db $f9,$f9,$8b
.ref40:
	.db $f9,$f9,$8b
.ref41:
	.db $f9,$f9,$8b
.ref42:
	.db $f9,$f9,$8b
.ref43:
	.db $f9,$f9,$8b
.ref44:
	.db $f9,$f9,$8b
.ref45:
	.db $f9,$f9,$8b
.ref46:
	.db $f9,$f9,$8b
.ref47:
	.db $f9,$f9,$8b
	.db $fd
	.dw .song0ch2loop

.song0ch3:
.song0ch3loop:
.ref48:
	.db $f9,$f9,$8b
.ref49:
	.db $f9,$f9,$8b
.ref50:
	.db $f9,$f9,$8b
.ref51:
	.db $f9,$f9,$8b
.ref52:
	.db $f9,$f9,$8b
.ref53:
	.db $f9,$f9,$8b
.ref54:
	.db $f9,$f9,$8b
.ref55:
	.db $f9,$f9,$8b
.ref56:
	.db $f9,$f9,$8b
.ref57:
	.db $f9,$f9,$8b
.ref58:
	.db $f9,$f9,$8b
.ref59:
	.db $f9,$f9,$8b
.ref60:
	.db $f9,$f9,$8b
.ref61:
	.db $f9,$f9,$8b
.ref62:
	.db $f9,$f9,$8b
.ref63:
	.db $f9,$f9,$8b
	.db $fd
	.dw .song0ch3loop

.song0ch4:
.song0ch4loop:
.ref64:
	.db $f9,$f9,$8b
.ref65:
	.db $f9,$f9,$8b
.ref66:
	.db $f9,$f9,$8b
.ref67:
	.db $f9,$f9,$8b
.ref68:
	.db $f9,$f9,$8b
.ref69:
	.db $f9,$f9,$8b
.ref70:
	.db $f9,$f9,$8b
.ref71:
	.db $f9,$f9,$8b
.ref72:
	.db $f9,$f9,$8b
.ref73:
	.db $f9,$f9,$8b
.ref74:
	.db $f9,$f9,$8b
.ref75:
	.db $f9,$f9,$8b
.ref76:
	.db $f9,$f9,$8b
.ref77:
	.db $f9,$f9,$8b
.ref78:
	.db $f9,$f9,$8b
.ref79:
	.db $f9,$f9,$8b
	.db $fd
	.dw .song0ch4loop
