;this file for FamiTone2 library generated by FamiStudio

superrunner_music_data:
	.db 1
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,307,256

.instruments:
	.db $f0 ;instrument 00 (Bass)
	.dw .env3, .env0, .env0
	.db $00
	.db $30 ;instrument 01 (HighHat)
	.dw .env1, .env0, .env0
	.db $00
	.db $30 ;instrument 02 (Instrument 1)
	.dw .env5, .env0, .env0
	.db $00
	.db $b0 ;instrument 03 (Instrument 2)
	.dw .env2, .env0, .env0
	.db $00
	.db $30 ;instrument 04 (Snare)
	.dw .env4, .env0, .env0
	.db $00

.samples:
.env0:
	.db $c0,$7f,$00,$00
.env1:
	.db $c9,$c6,$c0,$00,$02
.env2:
	.db $c5,$7f,$00,$00
.env3:
	.db $cf,$7f,$00,$00
.env4:
	.db $c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$08
.env5:
	.db $c8,$7f,$00,$00

.song0ch0:
	.db $fb, $01
.song0ch0loop:
.ref0:
	.db $84,$4e,$b3,$00,$83,$4e,$8b,$00,$4e,$8b,$00,$85,$54,$8f,$52,$93,$4e,$91,$4a,$b1,$00,$8b
.ref1:
	.db $81,$4a,$8b,$00,$4a,$8b,$00,$85,$52,$8f,$4e,$93,$4a,$91,$48,$b1,$00,$8f,$48,$8b,$00,$48,$8b,$00,$85,$4e,$8d
.ref2:
	.db $4a,$97,$48,$9d,$44,$b3,$48,$c3,$00,$a7
.ref3:
	.db $4e,$b3,$00,$83,$4e,$8b,$00,$4e,$8b,$00,$85,$54,$8f,$52,$93,$4e,$91,$4a,$b1,$00,$8b
	.db $ff,$1b
	.dw .ref1
	.db $ff,$0a
	.dw .ref2
.ref4:
	.db $4e,$b5,$00,$83,$52,$ad,$54,$a9,$52,$b5,$00,$8b
.ref5:
	.db $54,$ab,$58,$af,$54,$ad,$58,$ad,$00,$83,$5c,$97
.ref6:
	.db $58,$99,$4a,$99,$01,$4a,$99,$4e,$9f,$00,$83,$50,$b7,$54,$a1,$00
.ref7:
	.db $58,$99,$54,$9f,$50,$8f,$01,$50,$91,$00,$85,$48,$8b,$00,$48,$8b,$00,$85,$4e,$97,$00,$ad
.ref8:
	.db $f9,$e5
.ref9:
	.db $f9,$e5
.ref10:
	.db $f9,$e5
.ref11:
	.db $f9,$e5
.ref12:
	.db $f9,$e5
.ref13:
	.db $f9,$e5
.ref14:
	.db $f9,$e5
.ref15:
	.db $f9,$e5
.ref16:
	.db $f9,$e5
.ref17:
	.db $f9,$e5
.ref18:
	.db $f9,$e5
	.db $fd
	.dw .song0ch0loop

.song0ch1:
.song0ch1loop:
.ref19:
	.db $86,$4e,$dd,$00,$bb,$4a,$bf
.ref20:
	.db $9d,$00,$ad,$00,$95,$48,$af,$00,$c5
.ref21:
	.db $9d,$00,$99,$4e,$b1,$00,$ef
.ref22:
	.db $4e,$dd,$00,$bb,$4a,$bf
	.db $ff,$09
	.dw .ref20
	.db $ff,$07
	.dw .ref21
.ref23:
	.db $f9,$e5
.ref24:
	.db $f9,$e5
.ref25:
	.db $f9,$e5
.ref26:
	.db $f9,$e5
.ref27:
	.db $f9,$e5
.ref28:
	.db $f9,$e5
.ref29:
	.db $f9,$e5
.ref30:
	.db $f9,$e5
.ref31:
	.db $f9,$e5
.ref32:
	.db $f9,$e5
.ref33:
	.db $f9,$e5
.ref34:
	.db $f9,$e5
.ref35:
	.db $f9,$e5
.ref36:
	.db $f9,$e5
.ref37:
	.db $f9,$e5
	.db $fd
	.dw .song0ch1loop

.song0ch2:
.song0ch2loop:
.ref38:
	.db $f9,$e5
.ref39:
	.db $f9,$e5
.ref40:
	.db $f9,$e5
.ref41:
	.db $80,$44,$b3,$00,$83,$44,$8b,$00,$44,$8b,$00,$85,$4a,$8f,$48,$93,$44,$91,$40,$b1,$00,$8b
.ref42:
	.db $81,$40,$8b,$00,$40,$8b,$00,$85,$48,$8f,$44,$93,$40,$91,$3e,$b1,$00,$8f,$3e,$8b,$00,$3e,$8b,$00,$85,$44,$8d
.ref43:
	.db $40,$97,$3e,$9d,$3a,$b3,$3e,$c3,$00,$a7
.ref44:
	.db $f9,$e5
.ref45:
	.db $f9,$e5
.ref46:
	.db $f9,$e5
.ref47:
	.db $f9,$e5
.ref48:
	.db $f9,$e5
.ref49:
	.db $f9,$e5
.ref50:
	.db $f9,$e5
.ref51:
	.db $f9,$e5
.ref52:
	.db $f9,$e5
.ref53:
	.db $f9,$e5
.ref54:
	.db $f9,$e5
.ref55:
	.db $f9,$e5
.ref56:
	.db $f9,$e5
.ref57:
	.db $f9,$e5
.ref58:
	.db $f9,$e5
	.db $fd
	.dw .song0ch2loop

.song0ch3:
.song0ch3loop:
.ref59:
	.db $81,$88,$66,$b7,$82,$6c,$8b,$00,$6c,$8b,$00,$85,$88,$66,$f9,$81
.ref60:
	.db $81,$82,$6a,$8b,$00,$6a,$8b,$00,$85,$88,$66,$f9,$85,$82,$6a,$8b,$00,$6a,$8b,$00,$89,$88,$66,$89
.ref61:
	.db $f9,$e5
.ref62:
	.db $81,$66,$b7,$82,$6c,$8b,$00,$6c,$8b,$00,$85,$88,$66,$f9,$81
	.db $ff,$14
	.dw .ref60
.ref63:
	.db $f9,$e5
.ref64:
	.db $f9,$e5
.ref65:
	.db $f9,$e5
.ref66:
	.db $f9,$e5
.ref67:
	.db $f9,$ab,$00,$b5,$00
	.db $ff,$05
	.dw .ref67
.ref68:
	.db $f9,$e5
	.db $ff,$05
	.dw .ref67
	.db $ff,$05
	.dw .ref67
	.db $ff,$05
	.dw .ref67
.ref69:
	.db $f9,$e5
.ref70:
	.db $f9,$e5
.ref71:
	.db $f9,$e5
.ref72:
	.db $f9,$e5
.ref73:
	.db $f9,$e5
.ref74:
	.db $f9,$e5
	.db $fd
	.dw .song0ch3loop

.song0ch4:
.song0ch4loop:
.ref75:
	.db $bf,$58,$f9,$a3
.ref76:
	.db $f9,$e5
.ref77:
	.db $f9,$e5
.ref78:
	.db $f9,$e5
.ref79:
	.db $f9,$e5
.ref80:
	.db $f9,$e5
.ref81:
	.db $f9,$e5
.ref82:
	.db $f9,$e5
.ref83:
	.db $f9,$e5
.ref84:
	.db $f9,$e5
.ref85:
	.db $f9,$e5
.ref86:
	.db $f9,$e5
.ref87:
	.db $f9,$e5
.ref88:
	.db $f9,$e5
.ref89:
	.db $f9,$e5
.ref90:
	.db $f9,$e5
.ref91:
	.db $f9,$e5
.ref92:
	.db $f9,$e5
.ref93:
	.db $f9,$e5
.ref94:
	.db $f9,$e5
.ref95:
	.db $f9,$e5
	.db $fd
	.dw .song0ch4loop
